// AUTH
export const GET_USER_LOGIN = "GET_USER_LOGIN";

//EMPLOYEE
export const GET_INFO_EMPLOYEE = "GET_INFO_EMPLOYEE";
export const UPDATE_INFO_EMPLOYEE = "UPDATE_INFO_EMPLOYEE";

//NOTIFICATION
export const GET_NOTIFICATION_NOT_VIEW_BY_ID = "GET_NOTIFICATION_NOT_VIEW_BY_ID";
export const VIEW_NOTIFICATION_ID = "VIEW_NOTIFICATION_ID";
export const GET_ALL_NOTIFICATION = "GET_ALL_NOTIFICATION";
